Friday September 27th 2013 5:53 pm -04:00,Hiwhen i do commend contents = from_file.read() (place in video)  get back error:Traceback (most recent call last):  File <pyshell#83> line 1 in <module>    contents = otworz.read()AttributeError: tuple object has no attribute read file giełda eventów.txt i use in last lecture and everything was ok., Unresolved,0
Friday September 27th 2013 6:09 pm -04:00,my error was very stupid :Pcode should be: otworz = open(text r).Tom Enos thanks for answer :), Unresolved,0
Friday September 27th 2013 6:13 pm -04:00,Arun if you us python on windows maybe you have the same problem as me befor. check if in source of file you have /.If you only copy source of file like this C:\Users\ArturM\Desktop you do it wrong., Unresolved,0
