Sunday August 25th 2013 2:41 am -04:00,I get it and I get it right in the exersize but none of the names work in python3.3.  Why,None,0
Sunday August 25th 2013 2:34 am -04:00,I beleive that when the question has the word refers to then it wants the numerical answer not an explanation,None,0
Sunday August 25th 2013 3:25 am -04:00,I agree even though in this case the answer is self evident it is a good idea to double check your answer in python,None,0
Sunday August 25th 2013 2:48 am -04:00,From what I understand when it uses refers to it means the numerical result. when t says points to it maens the address,None,0
Sunday August 25th 2013 3:19 pm -04:00,I know that  you dont really know the address in the program I was just trying to explain that the address is like a container and reference is to what is in the container. It is not english but really a suedo english like maths is. programming has its own meaning for most of its language and then even different among different programming languages and programs and then if you do the reading even changes in the meaning of some words and some results are different in different versions of Pyphon. Confusing isnt it. I do beleive that things can be explained a bit better and I learned as much from the forum as I did from the lectures. I hope it does not get any harder.,None,0
Sunday August 25th 2013 2:29 am -04:00,1. Why does python(3.3.2)  give a name error for happy_day _happy and happy_45day this is both in the shell and direct in comandline also tried def happy_day and got error.2. Also why error using bigger(12) question.....................................................>>> happy_dayTraceback (most recent call last):  File <pyshell#11> line 1 in <module>    happy_dayNameError: name happy_day is not defined>>> 18happy_daySyntaxError: invalid syntax>>> _happyTraceback (most recent call last):  File <pyshell#13> line 1 in <module>    _happyNameError: name _happy is not defined>>> happy_45dayTraceback (most recent call last):  File <pyshell#14> line 1 in <module>    happy_45dayNameError: name happy_45day is not defined>>> bigger(12)Traceback (most recent call last):  File <pyshell#15> line 1 in <module>    bigger(12)NameError: name bigger is not defined>>> def bigger(x): return x**Xbigger(12)SyntaxError: invalid syntax>>> clrTraceback (most recent call last):  File <pyshell#20> line 1 in <module>    clrNameError: name clr is not defined>>> =3SyntaxError: invalid syntax>>> 2+35>>> 6-24,None,0
