Sunday September 1st 2013 2:11 pm -04:00,see change I made above to a1_test.py. I had the same errors as you did. After the change I did Run->Run module in IDLE and it worked fine, Resolved,1
