Tuesday September 10th 2013 6:01 pm -04:00,I am getting three errors on my get_complimentary_sequence function.  The error descriptions in the test results are describing tests that appear to be working when I run them in the shell:Q:  Have you tested your function on the example in the handout?A: Yes.  I run get_complimentary_sequence(AT) and get TA just as in the handout.Q: Have you tested your function on a sequence with multiple occurrences of each nucleotide?A: Yes and it appears to work without issue.  From the shell. >>> get_complimentary_sequence(TTTTAAAACCCCGGGG)AAAATTTTGGGGCCCCQ: Have you tested your function with all 4 nucleotides?A: Yes see result above.  Im not sure how to track down an error in my code since Ive run numerous tests all of which seem to work.  , Resolved,0
Tuesday September 10th 2013 6:27 pm -04:00,Ah...thanks.  I also had spelling errors in the function name for get_complement which did not produce errors in the evaluation.  Regardless I will see if that fixes the problem in about an hr.  Thanks!, Resolved,0
Friday September 13th 2013 5:55 pm -04:00,Thanks all.  The problem was indeed my spelling., Resolved,0
