Monday September 30th 2013 2:44 am -04:00,Got below error when I ran a3_driver in Mac OS X version 10.8.5. Does anyone know what wrong is? Any help is welcome please.   File /Users/home/assign3/a3_driver.py line 88 in <module>    words = a3.read_words(words_file)  File /Users/home/assign3/a3.py line 207 in read_words    for line in words_file:  File /Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/encodings/ascii.py line 26 in decode    return codecs.ascii_decode(input self.errors)[0]UnicodeDecodeError: ascii codec cant decode byte 0x9e in position 0: ordinal not in range(128), Unresolved,0
