Thursday September 26th 2013 8:13 pm -04:00,My read_words routine is on line 161 and works when a3.py is run by itself. When I run a3_driver.py I get the following error:>>> Traceback (most recent call last):  File C:\Users\roangl\Desktop\Ronnie\Coursera Courses\Python\How to Program\a3_driver.py line 88 in <module>    words = a3.read_words(words_file)  File C:\Users\roangl\Desktop\Ronnie\Coursera Courses\Python\How to Program\a3.py line 161 in read_words    words_file=open(words_filer)TypeError: invalid file: <_io.TextIOWrapper name=C:/Users/roangl/Desktop/Ronnie/Coursera Courses/Python/How to Program/wordlist1.txt mode=r encoding=cp1252>Apparently there is a problem with the routine because points are being taken off for the routines which are calling the open built in routine. The a3.py module was tested passing local filenames to the functions residing in the same folder as the module and acted as expected. tkinter fails to return the proper file. I had copied the input files from the browser to a NotePad text file., Unresolved,0
Friday September 27th 2013 3:52 pm -04:00,It works. You have to have a file handle to call the readline method. The way you get a file handle is to execute an open instruction. You take out the open instruction and the a2_driver program crashes put it in and it works fine. We are supposed to open a file to read it. The grading practices are making this course counter-intuitive if you were writing a program you would have to open a file to read it., Unresolved,0
Friday September 27th 2013 8:23 pm -04:00,Took the advice and solved the problem with the file reads. The type of the board during the development process was a list of strings but once the board_read routine was changed to create a list of list of strings full credit was awarded. Sorry to be so adamant about the process., Unresolved,0
Friday September 27th 2013 4:39 am -04:00,I was able to get my a3_driver.py to run but the grader gives me the following error when opening the board file:ERROR: DisabledBuiltinErrorCalling the open built-in is not permitted., Unresolved,0
Friday September 27th 2013 11:03 am -04:00,If you dont use open the handler is undefined.I corrected this and the whole program ran fine in a3_driver.It is the grader which is whacked. Everything runs the way it is supposed to now and yet I get 4 points taken off because of this error ( the name attribute had to be added to the routine for the program to work in the wrapper):ERROR: AttributeError_io.StringIO object has no attribute name, Unresolved,0
Friday September 27th 2013 8:34 pm -04:00,Sorry about the confusion. I developed the project running each subroutine independently on my own machine without tkinter or a3_driver.py. I thought it was correct because it created the right data structures. Then I learned about the name attribute of the file variable which introduced confusion. Basically the problem was solved for me by the posts of my fellow students. Such is the learning process I appreciate your help.Another problem was I created the board of the wrong type for the assignment specification I was going by the doc strings., Unresolved,0
