Thursday August 29th 2013 11:38 pm -04:00,It is like this:you defined the function sum with 2 parameters:>>> def sum(number1 number2):	return number1 + number2Up to this point the function prints nothing it just return the value of the sum of the two numbers.In the next statement:result = sum(1 3)you assign to the variable result the value returned by passing the values 1 and 3 as arguments in the function call of sum(number1 number2). Then you assign to the variable new_result the value obtained from the arithmetical operation of addition between the variable result and 1 which is 4 + 1 = 5 with the following line:new_result = result + 1Then you call the variable new_result so you get the 5.Hope this helps, Resolved,2
Thursday August 29th 2013 11:22 pm -04:00,If you use square_return (without quotes) you are calling the function square_return that you defined. Same for the function square_print. But you called answer_return which is unknown to the shell that why you get the error message., Unresolved,1
